CREATE TABLE [adi].[DHTX_HospitalCensus] (
    [HospitalCensusKey]                INT            IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                      VARCHAR (100)  NULL,
    [FileDate]                         DATE           NULL,
    [CreateDate]                       DATETIME       DEFAULT (sysdatetime()) NULL,
    [CreateBy]                         VARCHAR (100)  DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                 VARCHAR (100)  NULL,
    [LastUpdatedBy]                    VARCHAR (100)  DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                  DATETIME       DEFAULT (sysdatetime()) NULL,
    [DataDate]                         DATE           NULL,
    [DevotedID]                        VARCHAR (50)   NULL,
    [AuthorizationNumber]              VARCHAR (50)   NULL,
    [MBI]                              VARCHAR (50)   NULL,
    [MemberFirstName]                  VARCHAR (50)   NULL,
    [MemberMiddleInitial]              VARCHAR (20)   NULL,
    [MemberLastName]                   VARCHAR (50)   NULL,
    [MemberDOB]                        DATE           NULL,
    [PcpName]                          VARCHAR (50)   NULL,
    [PcpNPI]                           VARCHAR (15)   NULL,
    [PcpPracticeName]                  VARCHAR (20)   NULL,
    [PCPAddress]                       VARCHAR (100)  NULL,
    [PCPPhone]                         VARCHAR (20)   NULL,
    [PcpTIN]                           VARCHAR (20)   NULL,
    [PcpTINName]                       VARCHAR (50)   NULL,
    [AdmissionLevelofCare]             VARCHAR (20)   NULL,
    [AdmissionDate]                    DATE           NULL,
    [AdmissionDiagnosis]               VARCHAR (1000) NULL,
    [AdmissionDiagnosisDescription]    VARCHAR (5000) NULL,
    [FacilityName]                     VARCHAR (100)  NULL,
    [FacilityNPI]                      VARCHAR (20)   NULL,
    [DischargeDate]                    DATE           NULL,
    [DischargeDiagnosis]               VARCHAR (100)  NULL,
    [DischargeDisposition]             VARCHAR (50)   NULL,
    [AuthorizationRequestReceivedDate] DATE           NULL,
    [RequestingProviderFacilityNPI]    VARCHAR (20)   NULL,
    [RequestingProviderFacilityName]   VARCHAR (20)   NULL,
    [CensusSource]                     VARCHAR (20)   NULL,
    [OtherAuthorizations]              VARCHAR (20)   NULL,
    [ClaimNumbers]                     VARCHAR (500)  NULL,
    [Status]                           CHAR (1)       NULL,
    [ReportDate]                       DATE           NULL,
    [RowStatus]                        INT            DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([HospitalCensusKey] ASC)
);

