CREATE TABLE [adi].[DHTX_MedicalClaims] (
    [DHTXMedClaimsKey]               INT           IDENTITY (1, 1) NOT NULL,
    [ReportDate]                     DATE          NULL,
    [MemberID]                       VARCHAR (50)  NULL,
    [MemberFirstName]                VARCHAR (50)  NULL,
    [MemberLastName]                 VARCHAR (50)  NULL,
    [MemberBirthDate]                DATE          NULL,
    [MBI]                            VARCHAR (50)  NULL,
    [PcpName]                        VARCHAR (50)  NULL,
    [PcpNPI]                         VARCHAR (20)  NULL,
    [PcpPracticeName]                VARCHAR (50)  NULL,
    [PCPAddress]                     VARCHAR (50)  NULL,
    [PCPPhone]                       VARCHAR (20)  NULL,
    [PcpTIN]                         VARCHAR (20)  NULL,
    [PcpTINName]                     VARCHAR (20)  NULL,
    [ClaimType]                      VARCHAR (20)  NULL,
    [ClaimNumber]                    VARCHAR (20)  NULL,
    [ClaimLineNumber]                VARCHAR (20)  NULL,
    [TotAmtAllowed]                  MONEY         NULL,
    [TotAmtCopmt]                    MONEY         NULL,
    [TotAmtCharge]                   MONEY         NULL,
    [TotAmtPaid]                     MONEY         NULL,
    [TotAmtDenied]                   MONEY         NULL,
    [CheckNbr]                       VARCHAR (20)  NULL,
    [DateCreated]                    DATE          NULL,
    [DatePaid]                       DATE          NULL,
    [SvcFromDate]                    DATE          NULL,
    [SvcToDate]                      DATE          NULL,
    [AdjudicationStatus]             VARCHAR (10)  NULL,
    [PaymentStatus]                  VARCHAR (10)  NULL,
    [BillingProviderNPI]             VARCHAR (15)  NULL,
    [BillingProviderName]            VARCHAR (50)  NULL,
    [BillingProviderTIN]             VARCHAR (15)  NULL,
    [BillingProviderSpecialtyCode]   VARCHAR (15)  NULL,
    [BillingProviderSpecialtyName]   VARCHAR (50)  NULL,
    [RenderingProviderNPI]           VARCHAR (15)  NULL,
    [RenderingProviderName]          VARCHAR (50)  NULL,
    [RenderingProviderTIN]           VARCHAR (15)  NULL,
    [RenderingProviderSpecialtyCode] VARCHAR (15)  NULL,
    [RenderingProviderSpecialtyName] VARCHAR (50)  NULL,
    [SpecialtyCode]                  VARCHAR (15)  NULL,
    [SpecialtyDescription]           VARCHAR (100) NULL,
    [Units]                          VARCHAR (10)  NULL,
    [PlaceOfService]                 VARCHAR (100) NULL,
    [ProcedureCode]                  VARCHAR (50)  NULL,
    [ProcModifier]                   VARCHAR (50)  NULL,
    [ProcModifier2]                  VARCHAR (50)  NULL,
    [ProcModifier3]                  VARCHAR (50)  NULL,
    [ProcModifier4]                  VARCHAR (50)  NULL,
    [RevenueCode]                    VARCHAR (50)  NULL,
    [PrincipalDiagnosisCode]         VARCHAR (50)  NULL,
    [Icd10Diag1]                     VARCHAR (50)  NULL,
    [Icd10Diag2]                     VARCHAR (50)  NULL,
    [Icd10Diag3]                     VARCHAR (50)  NULL,
    [Icd10Diag4]                     VARCHAR (50)  NULL,
    [Icd10Diag5]                     VARCHAR (50)  NULL,
    [Icd10Diag6]                     VARCHAR (50)  NULL,
    [Icd10Diag7]                     VARCHAR (50)  NULL,
    [Icd10Diag8]                     VARCHAR (50)  NULL,
    [Icd10Diag9]                     VARCHAR (50)  NULL,
    [Icd10Diag10]                    VARCHAR (50)  NULL,
    [Icd10Diag11]                    VARCHAR (50)  NULL,
    [Icd10Diag12]                    VARCHAR (50)  NULL,
    [Icd10Diag13]                    VARCHAR (50)  NULL,
    [Icd10Diag14]                    VARCHAR (50)  NULL,
    [Icd10Diag15]                    VARCHAR (50)  NULL,
    [Icd10Diag16]                    VARCHAR (50)  NULL,
    [Icd10Diag17]                    VARCHAR (50)  NULL,
    [Icd10Diag18]                    VARCHAR (50)  NULL,
    [Icd10Diag19]                    VARCHAR (50)  NULL,
    [Icd10Diag20]                    VARCHAR (50)  NULL,
    [Icd10Diag21]                    VARCHAR (50)  NULL,
    [Icd10Diag22]                    VARCHAR (50)  NULL,
    [Icd10Diag23]                    VARCHAR (50)  NULL,
    [Icd10Diag24]                    VARCHAR (50)  NULL,
    [Icd10Diag25]                    VARCHAR (50)  NULL,
    [Icd10Diag26]                    VARCHAR (50)  NULL,
    [Icd10Diag27]                    VARCHAR (50)  NULL,
    [Icd10Diag28]                    VARCHAR (50)  NULL,
    [Icd10Diag29]                    VARCHAR (50)  NULL,
    [Icd10Diag30]                    VARCHAR (50)  NULL,
    [Icd10Diag31]                    VARCHAR (50)  NULL,
    [Icd10Diag32]                    VARCHAR (50)  NULL,
    [Icd10Diag33]                    VARCHAR (50)  NULL,
    [Icd10Diag34]                    VARCHAR (50)  NULL,
    [Icd10Diag35]                    VARCHAR (50)  NULL,
    [Icd10Diag36]                    VARCHAR (50)  NULL,
    [Icd10Diag37]                    VARCHAR (50)  NULL,
    [Icd10Diag38]                    VARCHAR (50)  NULL,
    [Icd10Diag39]                    VARCHAR (50)  NULL,
    [Icd10Diag40]                    VARCHAR (50)  NULL,
    [Icd10Diag41]                    VARCHAR (50)  NULL,
    [Icd10Diag42]                    VARCHAR (50)  NULL,
    [Icd10Diag43]                    VARCHAR (50)  NULL,
    [Icd10Diag44]                    VARCHAR (50)  NULL,
    [Icd10Diag45]                    VARCHAR (50)  NULL,
    [Icd10Diag46]                    VARCHAR (50)  NULL,
    [Icd10Diag47]                    VARCHAR (50)  NULL,
    [Icd10Diag48]                    VARCHAR (50)  NULL,
    [Icd10Proc1]                     VARCHAR (50)  NULL,
    [Icd10Proc1Date]                 DATE          NULL,
    [Icd10Proc2]                     VARCHAR (50)  NULL,
    [Icd10Proc2Date]                 DATE          NULL,
    [Icd10Proc3]                     VARCHAR (50)  NULL,
    [Icd10Proc3Date]                 DATE          NULL,
    [Icd10Proc4]                     VARCHAR (50)  NULL,
    [Icd10Proc4Date]                 DATE          NULL,
    [Icd10Proc5]                     VARCHAR (50)  NULL,
    [Icd10Proc5Date]                 DATE          NULL,
    [Icd10Proc6]                     VARCHAR (50)  NULL,
    [Icd10Proc6Date]                 DATE          NULL,
    [Icd10Proc7]                     VARCHAR (50)  NULL,
    [Icd10Proc7Date]                 DATE          NULL,
    [Icd10Proc8]                     VARCHAR (50)  NULL,
    [Icd10Proc8Date]                 DATE          NULL,
    [Icd10Proc9]                     VARCHAR (50)  NULL,
    [Icd10Proc9Date]                 DATE          NULL,
    [Icd10Proc10]                    VARCHAR (50)  NULL,
    [Icd10Proc10Date]                DATE          NULL,
    [Icd10Proc11]                    VARCHAR (50)  NULL,
    [Icd10Proc11Date]                DATE          NULL,
    [Icd10Proc12]                    VARCHAR (50)  NULL,
    [Icd10Proc12Date]                DATE          NULL,
    [Icd10Proc13]                    VARCHAR (50)  NULL,
    [Icd10Proc13Date]                DATE          NULL,
    [Icd10Proc14]                    VARCHAR (50)  NULL,
    [Icd10Proc14Date]                DATE          NULL,
    [Icd10Proc15]                    VARCHAR (50)  NULL,
    [Icd10Proc15Date]                DATE          NULL,
    [Icd10Proc16]                    VARCHAR (50)  NULL,
    [Icd10Proc16Date]                DATE          NULL,
    [Icd10Proc17]                    VARCHAR (50)  NULL,
    [Icd10Proc17Date]                DATE          NULL,
    [Icd10Proc18]                    VARCHAR (50)  NULL,
    [Icd10Proc18Date]                DATE          NULL,
    [Icd10Proc19]                    VARCHAR (50)  NULL,
    [Icd10Proc19Date]                DATE          NULL,
    [Icd10Proc20]                    VARCHAR (50)  NULL,
    [Icd10Proc20Date]                DATE          NULL,
    [Icd10Proc21]                    VARCHAR (50)  NULL,
    [Icd10Proc21Date]                DATE          NULL,
    [Icd10Proc22]                    VARCHAR (50)  NULL,
    [Icd10Proc22Date]                DATE          NULL,
    [Icd10Proc23]                    VARCHAR (50)  NULL,
    [Icd10Proc23Date]                DATE          NULL,
    [Icd10Proc24]                    VARCHAR (50)  NULL,
    [Icd10Proc24Date]                DATE          NULL,
    [Icd10Proc25]                    VARCHAR (50)  NULL,
    [Icd10Proc25Date]                DATE          NULL,
    [Icd10Proc26]                    VARCHAR (50)  NULL,
    [Icd10Proc26Date]                DATE          NULL,
    [Icd10Proc27]                    VARCHAR (50)  NULL,
    [Icd10Proc27Date]                DATE          NULL,
    [Icd10Proc28]                    VARCHAR (50)  NULL,
    [Icd10Proc28Date]                DATE          NULL,
    [Icd10Proc29]                    VARCHAR (50)  NULL,
    [Icd10Proc29Date]                DATE          NULL,
    [Icd10Proc30]                    VARCHAR (50)  NULL,
    [Icd10Proc30Date]                DATE          NULL,
    [Icd10Proc31]                    VARCHAR (50)  NULL,
    [Icd10Proc31Date]                DATE          NULL,
    [Icd10Proc32]                    VARCHAR (50)  NULL,
    [Icd10Proc32Date]                DATE          NULL,
    [Icd10Proc33]                    VARCHAR (50)  NULL,
    [Icd10Proc33Date]                DATE          NULL,
    [Icd10Proc34]                    VARCHAR (50)  NULL,
    [Icd10Proc34Date]                DATE          NULL,
    [Icd10Proc35]                    VARCHAR (50)  NULL,
    [Icd10Proc35Date]                DATE          NULL,
    [Icd10Proc36]                    VARCHAR (50)  NULL,
    [Icd10Proc36Date]                DATE          NULL,
    [Icd10Proc37]                    VARCHAR (50)  NULL,
    [Icd10Proc37Date]                DATE          NULL,
    [Icd10Proc38]                    VARCHAR (50)  NULL,
    [Icd10Proc38Date]                DATE          NULL,
    [Icd10Proc39]                    VARCHAR (50)  NULL,
    [Icd10Proc39Date]                DATE          NULL,
    [Icd10Proc40]                    VARCHAR (50)  NULL,
    [Icd10Proc40Date]                DATE          NULL,
    [Icd10Proc41]                    VARCHAR (50)  NULL,
    [Icd10Proc41Date]                DATE          NULL,
    [Icd10Proc42]                    VARCHAR (50)  NULL,
    [Icd10Proc42Date]                DATE          NULL,
    [Icd10Proc43]                    VARCHAR (50)  NULL,
    [Icd10Proc43Date]                DATE          NULL,
    [Icd10Proc44]                    VARCHAR (50)  NULL,
    [Icd10Proc44Date]                DATE          NULL,
    [Icd10Proc45]                    VARCHAR (50)  NULL,
    [Icd10Proc45Date]                DATE          NULL,
    [Icd10Proc46]                    VARCHAR (50)  NULL,
    [Icd10Proc46Date]                DATE          NULL,
    [Icd10Proc47]                    VARCHAR (50)  NULL,
    [Icd10Proc47Date]                DATE          NULL,
    [Icd10Proc48]                    VARCHAR (50)  NULL,
    [Icd10Proc48Date]                DATE          NULL,
    [OutOfNetwork]                   VARCHAR (50)  NULL,
    [Encounter]                      VARCHAR (50)  NULL,
    [AdmissionDate]                  DATE          NULL,
    [DischargeDate]                  DATE          NULL,
    [AdmissionType]                  VARCHAR (50)  NULL,
    [AdmissionSource]                VARCHAR (50)  NULL,
    [BillType]                       VARCHAR (50)  NULL,
    [DrgCode]                        VARCHAR (50)  NULL,
    [DischargeCode]                  VARCHAR (50)  NULL,
    [SrcFileName]                    VARCHAR (100) NULL,
    [FileDate]                       DATE          NULL,
    [CreateDate]                     DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                       VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]               VARCHAR (100) NULL,
    [LastUpdatedBy]                  VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                       DATE          NULL,
    [Status]                         CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([DHTXMedClaimsKey] ASC)
);

