CREATE TABLE [adi].[DHTX_QualitySupplementalData] (
    [DHTXQualitySupplementalDataKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                    VARCHAR (100) NULL,
    [FileDate]                       DATE          NULL,
    [CreateDate]                     DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                       VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]               VARCHAR (100) NULL,
    [LastUpdatedBy]                  VARCHAR (100) NULL,
    [LastUpdatedDate]                DATETIME      NULL,
    [DataDate]                       DATE          NULL,
    [ReportDate]                     DATE          NULL,
    [PatientName]                    VARCHAR (50)  NULL,
    [PatientID]                      VARCHAR (20)  NULL,
    [PatientDOB]                     DATE          NULL,
    [PCPName]                        VARCHAR (50)  NULL,
    [PCPNPI]                         VARCHAR (20)  NULL,
    [Practice]                       VARCHAR (20)  NULL,
    [AdmissionDate]                  DATE          NULL,
    [DischargeDate]                  DATE          NULL,
    [FacilityName]                   VARCHAR (50)  NULL,
    [FacilityAddress]                VARCHAR (50)  NULL,
    [MRPClaimSubmitted]              VARCHAR (50)  NULL,
    [MRPClaimServiceDate]            DATE          NULL,
    [PCPVisitWithin31Days]           VARCHAR (10)  NULL,
    [PCPClaimServiceDate]            DATE          NULL,
    PRIMARY KEY CLUSTERED ([DHTXQualitySupplementalDataKey] ASC)
);

