CREATE TABLE [adi].[DHTX_StarsActionableGapReport] (
    [StarsActionableGapReportKey] INT           IDENTITY (1, 1) NOT NULL,
    [ReportDate]                  DATE          NULL,
    [PatientName]                 VARCHAR (50)  NULL,
    [PatientID]                   VARCHAR (20)  NULL,
    [PatientDob]                  DATE          NULL,
    [PatientPhone]                VARCHAR (12)  NULL,
    [PatientMobilePhone]          VARCHAR (12)  NULL,
    [PcpName]                     VARCHAR (50)  NULL,
    [PcpNPI]                      VARCHAR (12)  NULL,
    [PcpPracticeName]             VARCHAR (50)  NULL,
    [PCPAddress]                  VARCHAR (100) NULL,
    [PCPPhone]                    VARCHAR (12)  NULL,
    [PcpTIN]                      VARCHAR (12)  NULL,
    [PcpTINName]                  VARCHAR (50)  NULL,
    [GapMeasureName]              VARCHAR (50)  NULL,
    [GapMeasureType]              VARCHAR (50)  NULL,
    [GapAction]                   VARCHAR (50)  NULL,
    [GapMeasureDetails]           VARCHAR (100) NULL,
    [NumberOfMemberGaps]          VARCHAR (10)  NULL,
    [SrcFileName]                 VARCHAR (100) NULL,
    [FileDate]                    DATE          NULL,
    [CreateDate]                  DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                    VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]            VARCHAR (100) NULL,
    [LastUpdatedBy]               VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]             DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                    DATE          NULL,
    [Status]                      CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([StarsActionableGapReportKey] ASC)
);

