CREATE TABLE [adi].[DHTX_MembershipEnrollment] (
    [MembershipEnrollmentKey]        INT           IDENTITY (1, 1) NOT NULL,
    [Devoted_Member_ID]              VARCHAR (50)  NULL,
    [Member_First_Name]              VARCHAR (50)  NULL,
    [Member_Last_Name]               VARCHAR (50)  NULL,
    [Member_Date_Of_Birth]           DATE          NULL,
    [Member_Address_Line_1]          VARCHAR (100) NULL,
    [Member_Address_Line_2]          VARCHAR (100) NULL,
    [Member_City]                    VARCHAR (50)  NULL,
    [Member_State]                   VARCHAR (10)  NULL,
    [Member_Zip]                     VARCHAR (10)  NULL,
    [Member_County]                  VARCHAR (50)  NULL,
    [Member_County_ID]               VARCHAR (50)  NULL,
    [Member_Phone]                   VARCHAR (20)  NULL,
    [Member_Language]                VARCHAR (50)  NULL,
    [Member_Gender]                  CHAR (1)      NULL,
    [Member_ESRD_Indicator]          VARCHAR (10)  NULL,
    [MBI_or_HICN]                    VARCHAR (50)  NULL,
    [Member_HICNs]                   VARCHAR (20)  NULL,
    [CMS_Contract_PBP]               VARCHAR (20)  NULL,
    [Line_Of_Business]               VARCHAR (50)  NULL,
    [Member_Dual_Eligible_Flag]      VARCHAR (20)  NULL,
    [Practice_Name]                  VARCHAR (100) NULL,
    [Devoted_PCP_ID]                 VARCHAR (20)  NULL,
    [PCP_Name]                       VARCHAR (100) NULL,
    [PCPAddressLine1]                VARCHAR (100) NULL,
    [PCPAddressLine2]                VARCHAR (100) NULL,
    [PCPCity]                        VARCHAR (50)  NULL,
    [PCPState]                       VARCHAR (50)  NULL,
    [PCPCounty]                      VARCHAR (50)  NULL,
    [PCPZipCode]                     VARCHAR (20)  NULL,
    [PCP_Effective_Date]             DATE          NULL,
    [PCP_End_Date]                   DATE          NULL,
    [Coverage_Effective_Date]        DATE          NULL,
    [Coverage_End_Date]              DATE          NULL,
    [Devoted_Contracting_Group_ID]   VARCHAR (50)  NULL,
    [Devoted_Contracting_Group_Name] VARCHAR (50)  NULL,
    [Member_Status]                  VARCHAR (50)  NULL,
    [File_Date]                      VARCHAR (20)  NULL,
    [SrcFileName]                    VARCHAR (100) NULL,
    [FileDate]                       DATE          NULL,
    [CreateDate]                     DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                       VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]               VARCHAR (100) NULL,
    [LastUpdatedBy]                  VARCHAR (100) NULL,
    [LastUpdatedDate]                DATETIME      NULL,
    [DataDate]                       DATE          NULL,
    [PCP_NPI]                        VARCHAR (50)  NULL,
    [Plan_Name]                      VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([MembershipEnrollmentKey] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ndx_DHTX_MbrShpEnrll_DataDate]
    ON [adi].[DHTX_MembershipEnrollment]([DataDate] ASC)
    INCLUDE([Devoted_Member_ID], [MBI_or_HICN]);

