CREATE TABLE [adi].[DHTX_StarsMeasureStatus] (
    [StarsMeasureStatusKey] INT           IDENTITY (1, 1) NOT NULL,
    [ReportDate]            DATE          NULL,
    [PatientName]           VARCHAR (50)  NULL,
    [PatientID]             VARCHAR (50)  NULL,
    [PatientDob]            DATE          NULL,
    [PatientPhone]          VARCHAR (12)  NULL,
    [PatientMobilePhone]    VARCHAR (12)  NULL,
    [PcpName]               VARCHAR (50)  NULL,
    [PcpNPI]                VARCHAR (20)  NULL,
    [PcpPracticeName]       VARCHAR (50)  NULL,
    [PCPAddress]            VARCHAR (100) NULL,
    [PCPPhone]              VARCHAR (12)  NULL,
    [PcpTIN]                VARCHAR (12)  NULL,
    [PcpTINName]            VARCHAR (100) NULL,
    [MeasureName]           VARCHAR (50)  NULL,
    [MeasureType]           VARCHAR (50)  NULL,
    [MeasureWeight]         VARCHAR (50)  NULL,
    [MeasureUnitType]       VARCHAR (50)  NULL,
    [MeasureCompliance]     VARCHAR (50)  NULL,
    [MemberWeight]          VARCHAR (50)  NULL,
    [SrcFileName]           VARCHAR (100) NULL,
    [FileDate]              DATE          NULL,
    [CreateDate]            DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]              VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]      VARCHAR (100) NULL,
    [LastUpdatedBy]         VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]       DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]              DATE          NULL,
    [Status]                CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([StarsMeasureStatusKey] ASC)
);

