CREATE TABLE [adi].[DHTX_MedAdherencePlans] (
    [DHTXMedAdherencePlansKey]    INT            IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                 VARCHAR (100)  NULL,
    [FileDate]                    DATE           NULL,
    [CreateDate]                  DATETIME       DEFAULT (sysdatetime()) NULL,
    [CreateBy]                    VARCHAR (100)  DEFAULT (suser_sname()) NULL,
    [OriginalFileName]            VARCHAR (100)  NULL,
    [LastUpdatedBy]               VARCHAR (100)  NULL,
    [LastUpdatedDate]             DATETIME       NULL,
    [DataDate]                    DATE           NULL,
    [ReportDate]                  DATE           NULL,
    [PatientName]                 VARCHAR (50)   NULL,
    [PatientID]                   VARCHAR (100)  NULL,
    [PatientDob]                  DATE           NULL,
    [PatientPhone]                VARCHAR (12)   NULL,
    [PatientMobilePhone]          VARCHAR (12)   NULL,
    [PcpName]                     VARCHAR (50)   NULL,
    [PcpNpi]                      VARCHAR (10)   NULL,
    [Practice]                    VARCHAR (50)   NULL,
    [PcpTIN]                      VARCHAR (10)   NULL,
    [MedicationAdherenceCategory] VARCHAR (50)   NULL,
    [MemberStatus]                VARCHAR (100)  NULL,
    [Needs90DaySupply]            CHAR (1)       NULL,
    [NextFillDueDate]             DATE           NULL,
    [LastFilledMedication]        VARCHAR (50)   NULL,
    [LastFillDate]                DATE           NULL,
    [LastFillDaysSupply]          VARCHAR (5)    NULL,
    [RefillsLeft]                 VARCHAR (5)    NULL,
    [DaysUntilGNA]                VARCHAR (5)    NULL,
    [DaysMissedInYear]            VARCHAR (5)    NULL,
    [PDC]                         DECIMAL (5, 1) NULL,
    [FirstFillDate]               DATE           NULL,
    [NumberOfFills]               VARCHAR (5)    NULL,
    [PrescriberName]              VARCHAR (50)   NULL,
    [PrescriberPhoneNumber]       VARCHAR (10)   NULL,
    [PharmacyName]                VARCHAR (50)   NULL,
    [PharmacyPhoneNumber]         VARCHAR (10)   NULL,
    [PharmacyAddress]             VARCHAR (100)  NULL,
    [DevotedPharmacyTeamNote]     VARCHAR (500)  NULL,
    [RowStatus]                   CHAR (1)       DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([DHTXMedAdherencePlansKey] ASC)
);

