CREATE TABLE [adi].[DHTX_PCPVIsit] (
    [DHTXPCPVisitKey]            INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                VARCHAR (100) NULL,
    [FileDate]                   DATE          NULL,
    [CreateDate]                 DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                   VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]           VARCHAR (100) NULL,
    [LastUpdatedBy]              VARCHAR (100) NULL,
    [LastUpdatedDate]            DATETIME      NULL,
    [DataDate]                   DATE          NULL,
    [ReportDate]                 DATE          NULL,
    [MemberID]                   VARCHAR (50)  NULL,
    [MemberFirstName]            VARCHAR (50)  NULL,
    [MemberLastName]             VARCHAR (50)  NULL,
    [MemberDOB]                  DATE          NULL,
    [PcpFirstName]               VARCHAR (50)  NULL,
    [PcpLastName]                VARCHAR (50)  NULL,
    [PcpNpi]                     VARCHAR (20)  NULL,
    [PcpTIN]                     VARCHAR (20)  NULL,
    [PcpAddress]                 VARCHAR (100) NULL,
    [PcpPracticeName]            VARCHAR (50)  NULL,
    [ComprehensiveVisitInYear]   VARCHAR (10)  NULL,
    [LastComprehensiveVisitDate] VARCHAR (10)  NULL,
    [PcpVisitInLast3Months]      VARCHAR (10)  NULL,
    [PcpVisitInYear]             VARCHAR (10)  NULL,
    [LastPcpVisitDate]           DATE          NULL,
    [LastPcpVisitFirstName]      VARCHAR (50)  NULL,
    [LastPcpVisitLastName]       VARCHAR (50)  NULL,
    [LastPcpVisitNPI]            VARCHAR (20)  NULL,
    [LastPcpVisitDiagnoses]      VARCHAR (50)  NULL,
    [RowStatus]                  TINYINT       DEFAULT ((0)) NULL,
    [MemberAddress]              VARCHAR (100) NULL,
    [MemberPhone]                VARCHAR (12)  NULL,
    [PcpPhone]                   VARCHAR (12)  NULL,
    [PcpTinName]                 VARCHAR (100) NULL,
    [MemberMobilePhone]          VARCHAR (12)  NULL,
    PRIMARY KEY CLUSTERED ([DHTXPCPVisitKey] ASC)
);

