CREATE TABLE [adi].[DHTX_QualityReports] (
    [DHTXQualityREportsKey]         INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                   VARCHAR (100) NULL,
    [FileDate]                      DATE          NULL,
    [CreateDate]                    DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                      VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]              VARCHAR (100) NULL,
    [LastUpdatedBy]                 VARCHAR (100) NULL,
    [LastUpdatedDate]               DATETIME      NULL,
    [DataDate]                      DATE          NULL,
    [ReportDate]                    DATE          NULL,
    [PatientName]                   VARCHAR (50)  NULL,
    [PatientID]                     VARCHAR (20)  NULL,
    [PatientDob]                    DATE          NULL,
    [PcpName]                       VARCHAR (50)  NULL,
    [PcpNpi]                        VARCHAR (20)  NULL,
    [Practice]                      VARCHAR (50)  NULL,
    [DateLastPcpVisit]              DATE          NULL,
    [DiabetesStatus]                VARCHAR (10)  NULL,
    [DiabetesRetina1Screen]         VARCHAR (50)  NULL,
    [DateLastEyeExam]               DATE          NULL,
    [DiabetesKidneyMonitoring]      VARCHAR (50)  NULL,
    [DiabetesHba1cControl]          VARCHAR (50)  NULL,
    [DiabetesHba1cControlReason]    VARCHAR (50)  NULL,
    [DateLastA1C]                   VARCHAR (50)  NULL,
    [LastA1CValue]                  VARCHAR (50)  NULL,
    [DiabetesStatinUse]             VARCHAR (50)  NULL,
    [RheumatoidArthritisManagement] VARCHAR (50)  NULL,
    [DiabetesAdherence]             VARCHAR (50)  NULL,
    [DiabetesLastFillDate]          DATE          NULL,
    [DiabetesNextFillDate]          DATE          NULL,
    [DiabetesDaysSupply]            VARCHAR (10)  NULL,
    [DiabetesDrug]                  VARCHAR (50)  NULL,
    [DiabetesSingleFill]            VARCHAR (50)  NULL,
    [HypertensionAdherence]         VARCHAR (50)  NULL,
    [HypertensionLastFillDate]      DATE          NULL,
    [HypertensionNextFillDate]      DATE          NULL,
    [HypertensionDaysSupply]        VARCHAR (50)  NULL,
    [HypertensionDrug]              VARCHAR (50)  NULL,
    [HypertensionSingleFill]        VARCHAR (50)  NULL,
    [CholesterolAdherence]          VARCHAR (50)  NULL,
    [CholesterolLastFillDate]       DATE          NULL,
    [CholesterolNextFillDate]       DATE          NULL,
    [CholesterolDaysSupply]         VARCHAR (50)  NULL,
    [CholesterolDrug]               VARCHAR (50)  NULL,
    [CholesterolSingleFill]         VARCHAR (50)  NULL,
    [PharmacyName]                  VARCHAR (20)  NULL,
    [PharmacyAddress]               VARCHAR (50)  NULL,
    [PharmacyTelephoneNumber]       VARCHAR (10)  NULL,
    [ControllingBloodPressure]      VARCHAR (50)  NULL,
    [ColorectalCancerScreening]     VARCHAR (20)  NULL,
    [CardiovascularStatinUse]       VARCHAR (20)  NULL,
    [RowStatus]                     TINYINT       DEFAULT ((0)) NULL,
    [PatientPhone]                  VARCHAR (12)  NULL,
    [PatientMobilePhone]            VARCHAR (12)  NULL,
    [PcpTIN]                        VARCHAR (20)  NULL,
    [LastPcpVisitName]              VARCHAR (50)  NULL,
    [LastPcpVisitNPI]               VARCHAR (10)  NULL,
    [HypertensionDiagnosisDate]     DATE          NULL,
    [ControllingBPReason]           VARCHAR (50)  NULL,
    [DateLastBPReading]             DATE          NULL,
    PRIMARY KEY CLUSTERED ([DHTXQualityREportsKey] ASC)
);

