CREATE TABLE [adi].[DHTX_StarsAdherenceQualityReports] (
    [StarsAdherenceEportKey]  INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]             VARCHAR (100) NULL,
    [FileDate]                DATE          NULL,
    [CreateDate]              DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]        VARCHAR (100) NULL,
    [LastUpdatedBy]           VARCHAR (100) NULL,
    [LastUpdatedDate]         DATETIME      NULL,
    [DataDate]                DATE          NULL,
    [ReportDate]              DATE          NULL,
    [PatientName]             VARCHAR (100) NULL,
    [PatientID]               VARCHAR (50)  NULL,
    [PatientDob]              DATE          NULL,
    [PcpName]                 VARCHAR (100) NULL,
    [PcpNpi]                  VARCHAR (20)  NULL,
    [Practice]                VARCHAR (20)  NULL,
    [Category]                VARCHAR (20)  NULL,
    [MemberStatus]            VARCHAR (500) NULL,
    [NextFillDueDate]         DATE          NULL,
    [LastFilledMedication]    VARCHAR (50)  NULL,
    [LastFillDate]            DATE          NULL,
    [Needs90DaySupply]        VARCHAR (20)  NULL,
    [DaysUntilGNA]            INT           NULL,
    [PrescriberName]          VARCHAR (100) NULL,
    [PrescriberPhoneNumber]   VARCHAR (20)  NULL,
    [PharmacyName]            VARCHAR (50)  NULL,
    [PharmacyPhoneNumber]     VARCHAR (12)  NULL,
    [PharmacyAddress]         VARCHAR (100) NULL,
    [RowStatus]               TINYINT       DEFAULT ((0)) NULL,
    [PatientPhone]            VARCHAR (12)  NULL,
    [PatientMobilePhone]      VARCHAR (12)  NULL,
    [PcpTIN]                  VARCHAR (20)  NULL,
    [RefillsLeft]             VARCHAR (10)  NULL,
    [DaysMissedInYear]        VARCHAR (10)  NULL,
    [DevotedPharmacyTeamNote] VARCHAR (500) NULL,
    [PcpPracticeName]         VARCHAR (100) NULL,
    [PcpAddress]              VARCHAR (100) NULL,
    [PcpPhone]                VARCHAR (20)  NULL,
    [PcpTinName]              VARCHAR (100) NULL,
    [LastFillDaySupply]       VARCHAR (10)  NULL,
    [PDC]                     VARCHAR (50)  NULL,
    [FirstFillDate]           DATE          NULL,
    [NumberOfFills]           VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([StarsAdherenceEportKey] ASC)
);

