CREATE TABLE [adi].[DHTX_Eligibility] (
    [EligibilityKey]         INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]            VARCHAR (100) NULL,
    [FileDate]               DATE          NULL,
    [CreateDate]             DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]               VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]       VARCHAR (100) NULL,
    [LastUpdatedBy]          VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]        DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]               DATE          NULL,
    [ReportDate]             DATE          NULL,
    [EffectiveMonth]         DATE          NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [MBI]                    VARCHAR (50)  NULL,
    [MemberFirstName]        VARCHAR (50)  NULL,
    [MemberMiddleInitial]    VARCHAR (10)  NULL,
    [MemberLastName]         VARCHAR (50)  NULL,
    [MemberDOB]              DATE          NULL,
    [MemberAddressLine1]     VARCHAR (100) NULL,
    [MemberAddressLine2]     VARCHAR (100) NULL,
    [MemberCity]             VARCHAR (50)  NULL,
    [MemberState]            CHAR (2)      NULL,
    [MemberZip]              VARCHAR (10)  NULL,
    [MemberCounty]           VARCHAR (50)  NULL,
    [MemberPhone]            VARCHAR (20)  NULL,
    [MemberMobilePhone]      VARCHAR (20)  NULL,
    [MemberEmail]            VARCHAR (20)  NULL,
    [MemberLanguage]         VARCHAR (20)  NULL,
    [MemberGender]           CHAR (1)      NULL,
    [MemberDeathDate]        DATE          NULL,
    [PlanName]               VARCHAR (20)  NULL,
    [CMSContractPBP]         VARCHAR (20)  NULL,
    [DualEligibleStatus]     CHAR (2)      NULL,
    [MedicareSecondaryPayer] VARCHAR (20)  NULL,
    [Hospice]                CHAR (1)      NULL,
    [MemberESRDIndicator]    VARCHAR (6)   NULL,
    [PcpFirstName]           VARCHAR (20)  NULL,
    [PcpLastName]            VARCHAR (20)  NULL,
    [PcpNPI]                 VARCHAR (20)  NULL,
    [DevotedPCPID]           VARCHAR (20)  NULL,
    [PcpPracticeName]        VARCHAR (20)  NULL,
    [PcpTIN]                 VARCHAR (20)  NULL,
    [PcpTINName]             VARCHAR (20)  NULL,
    [PCPAddressLine1]        VARCHAR (50)  NULL,
    [PCPAddressLine2]        VARCHAR (50)  NULL,
    [PCPCity]                VARCHAR (20)  NULL,
    [PCPState]               CHAR (2)      NULL,
    [PCPCounty]              VARCHAR (20)  NULL,
    [PCPZipCode]             VARCHAR (10)  NULL,
    [PCPPhone]               VARCHAR (20)  NULL,
    [AgentOfRecord]          VARCHAR (20)  NULL,
    [NewThisMonth]           VARCHAR (20)  NULL,
    [MonthEndStatus]         VARCHAR (20)  NULL,
    [Status]                 CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([EligibilityKey] ASC)
);

