CREATE TABLE [adi].[DHTX_StarsMemberStatus] (
    [StarsMemberStatusKey]                       INT           IDENTITY (1, 1) NOT NULL,
    [ReportDate]                                 DATE          NULL,
    [PatientName]                                VARCHAR (50)  NULL,
    [PatientID]                                  VARCHAR (50)  NULL,
    [PatientDob]                                 DATE          NULL,
    [PatientPhone]                               VARCHAR (12)  NULL,
    [PatientMobilePhone]                         VARCHAR (12)  NULL,
    [PcpName]                                    VARCHAR (50)  NULL,
    [PcpNPI]                                     VARCHAR (20)  NULL,
    [PcpPracticeName]                            VARCHAR (50)  NULL,
    [PCPAddress]                                 VARCHAR (100) NULL,
    [PCPPhone]                                   VARCHAR (12)  NULL,
    [PcpTIN]                                     VARCHAR (12)  NULL,
    [PcpTINName]                                 VARCHAR (100) NULL,
    [DateLastPcpVisit]                           DATE          NULL,
    [LastPCPVisitName]                           VARCHAR (50)  NULL,
    [LastPcpVisitNPI]                            VARCHAR (20)  NULL,
    [DiabetesStatus]                             VARCHAR (50)  NULL,
    [DiabetesRetinalScreen]                      VARCHAR (50)  NULL,
    [DateLastEyeExam]                            VARCHAR (50)  NULL,
    [DiabetesKidneyMonitoring]                   VARCHAR (50)  NULL,
    [DiabetesHba1cControl]                       VARCHAR (50)  NULL,
    [DiabetesHba1cControlReason]                 VARCHAR (50)  NULL,
    [DateLastA1c]                                VARCHAR (50)  NULL,
    [LastA1CValue]                               VARCHAR (50)  NULL,
    [LastA1CSource]                              VARCHAR (50)  NULL,
    [ControllingBloodPressure]                   VARCHAR (50)  NULL,
    [HypertensionDiagnosisDate]                  DATE          NULL,
    [ControllingBPReason]                        VARCHAR (50)  NULL,
    [DateLastBPReading]                          DATE          NULL,
    [LastBPReadingValue]                         VARCHAR (50)  NULL,
    [LastBPSource]                               VARCHAR (50)  NULL,
    [ColorectalCancerScreening]                  VARCHAR (50)  NULL,
    [BreastCancerScreening]                      VARCHAR (50)  NULL,
    [COAMedicationReview]                        VARCHAR (50)  NULL,
    [COAFunctionalStatusAssessment]              VARCHAR (50)  NULL,
    [COAPainAssessment]                          VARCHAR (50)  NULL,
    [DiabetesStatinUse]                          VARCHAR (50)  NULL,
    [CardiovascularStatinUse]                    VARCHAR (50)  NULL,
    [OsteoporosisManagementForWomenWithFracture] VARCHAR (50)  NULL,
    [OMWFractureDate]                            DATE          NULL,
    [SrcFileName]                                VARCHAR (100) NULL,
    [FileDate]                                   DATE          NULL,
    [CreateDate]                                 DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                                   VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                           VARCHAR (100) NULL,
    [LastUpdatedBy]                              VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                            DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                                   DATE          NULL,
    [Status]                                     CHAR (1)      CONSTRAINT [DF_Status] DEFAULT ((0)) NULL,
    [LoadDate]                                   DATE          NULL,
    PRIMARY KEY CLUSTERED ([StarsMemberStatusKey] ASC)
);

