CREATE TABLE [adi].[DHTX_PharmacyClaims] (
    [DHTXPharmacyClaimsKey] INT             IDENTITY (1, 1) NOT NULL,
    [SrcFileName]           VARCHAR (100)   NULL,
    [FileDate]              DATE            NULL,
    [CreateDate]            DATETIME        DEFAULT (sysdatetime()) NULL,
    [CreateBy]              VARCHAR (100)   DEFAULT (suser_sname()) NULL,
    [OriginalFileName]      VARCHAR (100)   NULL,
    [LastUpdatedBy]         VARCHAR (100)   NULL,
    [LastUpdatedDate]       DATETIME        NULL,
    [DataDate]              DATE            NULL,
    [DevotedID]             VARCHAR (50)    NULL,
    [MemberFirstName]       VARCHAR (20)    NULL,
    [MemberLastName]        VARCHAR (20)    NULL,
    [MemberBirthDate]       DATE            NULL,
    [MemberMedicareID]      VARCHAR (50)    NULL,
    [ClaimNumber]           VARCHAR (50)    NULL,
    [DateFilled]            DATE            NULL,
    [DatePaid]              DATE            NULL,
    [TotalPaidAmount]       NUMERIC (18, 2) NULL,
    [MemberPaidAmount]      NUMERIC (18, 2) NULL,
    [PlanPaidAmount]        NUMERIC (18, 2) NULL,
    [PrescriberIDType]      VARCHAR (10)    NULL,
    [PrescriberID]          VARCHAR (50)    NULL,
    [PrescriberFirstName]   VARCHAR (50)    NULL,
    [PrescriberLastName]    VARCHAR (20)    NULL,
    [PrescriberAddress]     VARCHAR (50)    NULL,
    [PrescriberAddressCity] VARCHAR (20)    NULL,
    [PrescriberAddressZip]  VARCHAR (10)    NULL,
    [PharmacyIDType]        VARCHAR (10)    NULL,
    [PharmacyID]            VARCHAR (20)    NULL,
    [PharmacyName]          VARCHAR (50)    NULL,
    [PharmacyAddressLine1]  VARCHAR (50)    NULL,
    [PharmacyAddressLine2]  VARCHAR (50)    NULL,
    [PharmacyAddressCity]   VARCHAR (20)    NULL,
    [PharmacyAddressState]  VARCHAR (20)    NULL,
    [PharmacyAddressZip]    VARCHAR (10)    NULL,
    [ProductNDC]            VARCHAR (50)    NULL,
    [ProductName]           VARCHAR (50)    NULL,
    [ClaimStatus]           VARCHAR (10)    NULL,
    [QuantityDispensed]     DECIMAL (5, 2)  NULL,
    [DaysSupply]            INT             NULL,
    [FormularyTier]         VARCHAR (50)    NULL,
    [FillNumber]            VARCHAR (50)    NULL,
    [NumberOfRefills]       INT             NULL,
    [PcpNPI]                VARCHAR (50)    NULL,
    [PcpFirstName]          VARCHAR (20)    NULL,
    [PcpLastName]           VARCHAR (10)    NULL,
    [DevotedPCPID]          VARCHAR (20)    NULL,
    [PcpAddressLine1]       VARCHAR (50)    NULL,
    [PcpAddressLine2]       VARCHAR (50)    NULL,
    [PcpAddressCity]        VARCHAR (20)    NULL,
    [PcpAddressState]       VARCHAR (10)    NULL,
    [PcpAddressCounty]      VARCHAR (20)    NULL,
    [PcpAddressZip]         VARCHAR (10)    NULL,
    [PcpGroupID]            VARCHAR (20)    NULL,
    [PcpPracticeName]       VARCHAR (100)   NULL,
    [PCPPhone]              VARCHAR (20)    NULL,
    [PcpTIN]                VARCHAR (12)    NULL,
    [PcpTINName]            VARCHAR (50)    NULL,
    [IsGenericProduct]      CHAR (1)        NULL,
    [GenericProductName]    CHAR (50)       NULL,
    [ReportDate]            DATE            NULL,
    [Status]                CHAR (1)        NULL,
    [LoadDate]              DATE            NULL,
    PRIMARY KEY CLUSTERED ([DHTXPharmacyClaimsKey] ASC)
);

