CREATE TABLE [adi].[DHTX_Census] (
    [DHTXCensusKey]                    INT            IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                      VARCHAR (100)  NULL,
    [FileDate]                         DATE           NULL,
    [CreateDate]                       DATETIME       DEFAULT (sysdatetime()) NULL,
    [CreateBy]                         VARCHAR (100)  DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                 VARCHAR (100)  NULL,
    [LastUpdatedBy]                    VARCHAR (100)  NULL,
    [LastUpdatedDate]                  DATETIME       NULL,
    [DataDate]                         DATE           NULL,
    [DevotedMemberID]                  VARCHAR (50)   NULL,
    [EpisodeID]                        VARCHAR (50)   NULL,
    [MBI_HICN]                         VARCHAR (10)   NULL,
    [MemberFirstName]                  VARCHAR (20)   NULL,
    [MemberMiddleInitial]              VARCHAR (20)   NULL,
    [MemberLastName]                   VARCHAR (20)   NULL,
    [MemberDateOfBirth]                DATE           NULL,
    [CurrentlyAssignedGroup]           VARCHAR (10)   NULL,
    [PCP_NPI]                          VARCHAR (20)   NULL,
    [PCPCounty]                        VARCHAR (20)   NULL,
    [Devoted_PCP_ID]                   VARCHAR (20)   NULL,
    [AdmissionLevelCare]               VARCHAR (10)   NULL,
    [AdmissionDate]                    DATE           NULL,
    [DischargeDate]                    DATE           NULL,
    [FacilityName]                     VARCHAR (50)   NULL,
    [FacilityNPI]                      VARCHAR (50)   NULL,
    [Diagnosis]                        VARCHAR (10)   NULL,
    [PatientComplaint]                 VARCHAR (1000) NULL,
    [AuthNumbe]                        VARCHAR (20)   NULL,
    [AuthorizationRequestReceivedDate] DATE           NULL,
    [RequestingProvider_FacilityNPI]   VARCHAR (20)   NULL,
    [RequestingProvider_FacilityName]  VARCHAR (100)  NULL,
    [RowStatus]                        TINYINT        DEFAULT ((0)) NULL,
    [PCPName]                          VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([DHTXCensusKey] ASC)
);

