CREATE TABLE [adi].[DHTX_EnrollmentChanges] (
    [EnrollmentChangesKey]     INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]              VARCHAR (100) NULL,
    [FileDate]                 DATE          NULL,
    [CreateDate]               DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                 VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]         VARCHAR (100) NULL,
    [LastUpdatedBy]            VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]          DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                 DATE          NULL,
    [ReportDate]               DATE          NULL,
    [EffectiveDate]            DATE          NULL,
    [FutureChange]             VARCHAR (10)  NULL,
    [Status]                   CHAR (1)      NULL,
    [MemberID]                 VARCHAR (10)  NULL,
    [MBI]                      VARCHAR (50)  NULL,
    [MemberFirstName]          VARCHAR (50)  NULL,
    [MemberMiddleInitial]      VARCHAR (20)  NULL,
    [MemberLastName]           VARCHAR (50)  NULL,
    [MemberDOB]                DATE          NULL,
    [MemberAddressLine1]       VARCHAR (50)  NULL,
    [MemberAddressLine2]       VARCHAR (50)  NULL,
    [MemberCity]               VARCHAR (50)  NULL,
    [MemberState]              VARCHAR (50)  NULL,
    [MemberZip]                VARCHAR (10)  NULL,
    [MemberPhone]              VARCHAR (12)  NULL,
    [MemberMobilePhone]        VARCHAR (12)  NULL,
    [MemberEmail]              VARCHAR (50)  NULL,
    [PcpFirstName]             VARCHAR (50)  NULL,
    [PcpLastName]              VARCHAR (50)  NULL,
    [PcpNPI]                   VARCHAR (12)  NULL,
    [PcpPracticeName]          VARCHAR (50)  NULL,
    [PCPAddress]               VARCHAR (50)  NULL,
    [PCPPhone]                 VARCHAR (50)  NULL,
    [PcpTIN]                   VARCHAR (12)  NULL,
    [PcpTINName]               VARCHAR (50)  NULL,
    [DevotedPlan]              VARCHAR (50)  NULL,
    [DevotedPlanName]          VARCHAR (50)  NULL,
    [EnrollmentEndDate]        DATE          NULL,
    [DisenrollmentProcessDate] DATE          NULL,
    [DisenrollmentSourceID]    VARCHAR (50)  NULL,
    [DisenrollmentPlanLeftTo]  VARCHAR (50)  NULL,
    [DisenrollmentReasonCode]  VARCHAR (50)  NULL,
    [DisenrollmentReason]      VARCHAR (50)  NULL,
    [VoluntaryDisenrollment]   VARCHAR (50)  NULL,
    [LoadDate]                 DATE          NULL,
    PRIMARY KEY CLUSTERED ([EnrollmentChangesKey] ASC)
);

