CREATE TABLE [adi].[DHTX_EligibilityMonthly] (
    [EligibilityMonthlyKey]  INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]            VARCHAR (100) NULL,
    [FileDate]               DATE          NULL,
    [CreateDate]             DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]               VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]       VARCHAR (100) NULL,
    [LastUpdatedBy]          VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]        DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]               DATE          NULL,
    [ReportDate]             DATE          NULL,
    [EffectiveMonth]         VARCHAR (10)  NULL,
    [MemberID]               VARCHAR (50)  NULL,
    [MBI]                    VARCHAR (50)  NULL,
    [MemberFirstName]        VARCHAR (50)  NULL,
    [MemberMiddleInitial]    VARCHAR (20)  NULL,
    [MemberLastName]         VARCHAR (50)  NULL,
    [MemberDOB]              DATE          NULL,
    [MemberAddressLine1]     VARCHAR (100) NULL,
    [MemberAddressLine2]     VARCHAR (100) NULL,
    [MemberCity]             VARCHAR (50)  NULL,
    [MemberState]            VARCHAR (20)  NULL,
    [MemberZip]              VARCHAR (10)  NULL,
    [MemberCounty]           VARCHAR (50)  NULL,
    [MemberPhone]            VARCHAR (20)  NULL,
    [MemberMobilePhone]      VARCHAR (20)  NULL,
    [MemberEmail]            VARCHAR (50)  NULL,
    [MemberLanguage]         VARCHAR (20)  NULL,
    [MemberGender]           VARCHAR (10)  NULL,
    [MemberDeathDate]        DATE          NULL,
    [PlanName]               VARCHAR (50)  NULL,
    [CMSContractPBP]         VARCHAR (50)  NULL,
    [DualEligibleStatus]     VARCHAR (20)  NULL,
    [MedicareSecondaryPayer] VARCHAR (50)  NULL,
    [Hospice]                VARCHAR (50)  NULL,
    [MemberESRDIndicator]    VARCHAR (50)  NULL,
    [PcpFirstName]           VARCHAR (50)  NULL,
    [PcpLastName]            VARCHAR (50)  NULL,
    [PcpNpi]                 VARCHAR (12)  NULL,
    [DevotedPCPID]           VARCHAR (50)  NULL,
    [PcpPracticeName]        VARCHAR (50)  NULL,
    [PcpTIN]                 VARCHAR (20)  NULL,
    [PcpTINName]             VARCHAR (50)  NULL,
    [PcpAddressLine1]        VARCHAR (50)  NULL,
    [PcpAddressLine2]        VARCHAR (50)  NULL,
    [PcpCity]                VARCHAR (20)  NULL,
    [PcpState]               VARCHAR (10)  NULL,
    [PcpCounty]              VARCHAR (20)  NULL,
    [PcpZipCode]             VARCHAR (10)  NULL,
    [PcpPhone]               VARCHAR (20)  NULL,
    [AgentOfRecord]          VARCHAR (50)  NULL,
    [NewThisMonth]           VARCHAR (20)  NULL,
    [MonthEndStatus]         VARCHAR (20)  NULL,
    [Status]                 CHAR (1)      CONSTRAINT [df_rstatus] DEFAULT ((0)) NULL,
    [EnrollmentStartDate]    DATE          NULL,
    [EnrollmentEndDate]      DATE          NULL,
    [PCPStartDate]           DATE          NULL,
    [PCPEndDate]             DATE          NULL,
    [DevotedPCPGroupID]      VARCHAR (50)  NULL,
    [LineOfBusiness]         VARCHAR (100) NULL,
    [LoadDate]               DATE          NULL,
    PRIMARY KEY CLUSTERED ([EligibilityMonthlyKey] ASC)
);

