CREATE TABLE [ast].[MbrStg2_MbrData] (
    [mbrStg2_MbrDataUrn]          INT             IDENTITY (1, 1) NOT NULL,
    [ClientSubscriberId]          VARCHAR (50)    NULL,
    [ClientKey]                   VARCHAR (50)    NULL,
    [MstrMrnKey]                  NUMERIC (15)    CONSTRAINT [DF_astMbrStg2_MbrData_MstrMrnKey] DEFAULT ((-1)) NOT NULL,
    [LoadType]                    VARCHAR (5)     CONSTRAINT [DF_astMbrStg2_MbrData_LoadType] DEFAULT ('P') NULL,
    [mbrLastName]                 VARCHAR (100)   NULL,
    [mbrFirstName]                VARCHAR (100)   NULL,
    [mbrMiddleName]               VARCHAR (100)   CONSTRAINT [df_MI] DEFAULT ('') NULL,
    [mbrSSN]                      VARCHAR (15)    NULL,
    [mbrGENDER]                   VARCHAR (5)     CONSTRAINT [df_gender] DEFAULT ('') NULL,
    [mbrDob]                      DATE            NULL,
    [mbrInsuranceCardIdNum]       VARCHAR (20)    NULL,
    [mbrMEDICAID_NO]              VARCHAR (15)    NULL,
    [mbrMEDICARE_ID]              VARCHAR (15)    NULL,
    [HICN]                        VARCHAR (11)    NULL,
    [MBI]                         VARCHAR (11)    NULL,
    [mbrEthnicity]                VARCHAR (20)    CONSTRAINT [DF_EmbrEthnicity] DEFAULT ('') NULL,
    [mbrRace]                     VARCHAR (20)    CONSTRAINT [DF_mbrRace] DEFAULT ('') NULL,
    [mbrPrimaryLanguage]          VARCHAR (20)    NULL,
    [prvNPI]                      VARCHAR (10)    NULL,
    [prvTIN]                      VARCHAR (10)    NULL,
    [prvAutoAssign]               VARCHAR (10)    NULL,
    [prvClientEffective]          DATE            NULL,
    [prvClientExpiration]         DATE            NULL,
    [plnProductPlan]              VARCHAR (50)    NULL,
    [plnProductSubPlan]           VARCHAR (100)   NULL,
    [plnProductSubPlanName]       VARCHAR (50)    NULL,
    [plnMbrIsDualCoverage]        VARCHAR (20)    NULL,
    [plnClientPlanEffective]      DATE            NULL,
    [rspLastName]                 VARCHAR (100)   NULL,
    [rspFirstName]                VARCHAR (100)   NULL,
    [rspAddress1]                 VARCHAR (100)   NULL,
    [rspAddress2]                 VARCHAR (100)   NULL,
    [rspCITY]                     VARCHAR (65)    NULL,
    [rspSTATE]                    CHAR (25)       NULL,
    [rspZIP]                      VARCHAR (20)    NULL,
    [rspPhone]                    VARCHAR (30)    NULL,
    [SrcFileName]                 VARCHAR (100)   NULL,
    [AdiTableName]                VARCHAR (100)   NULL,
    [AdiKey]                      INT             NULL,
    [stgRowStatus]                VARCHAR (20)    CONSTRAINT [DF_astMbrStg2_MbrData_StgRowStatus] DEFAULT ('Not Valid') NOT NULL,
    [LoadDate]                    DATE            NULL,
    [DataDate]                    DATE            NULL,
    [CreateDate]                  DATETIME        CONSTRAINT [DF_astMbrStg2_MbrData_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]                    VARCHAR (50)    CONSTRAINT [DF_astMbrStg2_MbrData_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [MbrMemberKey]                INT             NULL,
    [MbrPlanKey]                  INT             NULL,
    [MbrPcpKey]                   INT             NULL,
    [MbrCsPlanKey]                INT             NULL,
    [MbrLoadHistoryKey]           INT             NULL,
    [plnClientPlanEndDate]        DATE            NULL,
    [stgRowAction]                VARCHAR (10)    DEFAULT ('Upsert') NOT NULL,
    [Member_Dual_Eligible_Flag]   VARCHAR (20)    NULL,
    [MbrState]                    CHAR (2)        NOT NULL,
    [MemberStatus]                VARCHAR (50)    NULL,
    [MemberOriginalEffectiveDate] DATE            NULL,
    [RiskScore]                   DECIMAL (5)     NULL,
    [OpportunityScore]            DECIMAL (5)     NULL,
    [MbrCity]                     VARCHAR (50)    NULL,
    [SubscriberID_Client]         VARCHAR (50)    NULL,
    [Indicator834]                VARCHAR (50)    NULL,
    [MbrDOD]                      DATE            DEFAULT ('') NULL,
    [ProviderChapter]             VARCHAR (50)    NULL,
    [MemberOriginalEndDate]       DATE            NULL,
    [EffectiveDate]               DATE            NULL,
    [MbrNPIFlg]                   BIT             DEFAULT ((0)) NULL,
    [MbrPlnFlg]                   BIT             DEFAULT ((0)) NULL,
    [MbrFlgCount]                 TINYINT         DEFAULT ((0)) NULL,
    [ProviderFirstName]           VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderMI]                  VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderLastName]            VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderPracticeName]        VARCHAR (100)   DEFAULT ('') NULL,
    [ProviderAddressLine1]        VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderAddressLine2]        VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderCity]                VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderCounty]              VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderZip]                 VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderPhone]               VARCHAR (50)    DEFAULT ('') NULL,
    [ProviderSpecialty]           VARCHAR (100)   DEFAULT ('') NULL,
    [ProviderNetwork]             VARCHAR (50)    DEFAULT ('') NULL,
    [SpecialistStatus]            VARCHAR (50)    DEFAULT ('') NULL,
    [GroupOrPrivatePractice]      VARCHAR (20)    DEFAULT ('') NULL,
    [ProviderPOD]                 VARCHAR (50)    DEFAULT ('') NULL,
    [AceRiskScore]                DECIMAL (5, 2)  NULL,
    [AceRiskScoreLevel]           DECIMAL (5, 2)  NULL,
    [ClientRiskScore]             DECIMAL (10, 2) NULL,
    [ClientRiskScoreLevel]        DECIMAL (25, 2) NULL,
    [RiskScoreUtilization]        DECIMAL (5, 2)  NULL,
    [RiskScoreClinical]           DECIMAL (5, 2)  NULL,
    [RiskScoreHRA]                DECIMAL (5, 2)  NULL,
    [RiskScorePlaceHolder]        DECIMAL (5, 2)  NULL,
    [srcNPI]                      VARCHAR (50)    NULL,
    [srcPln]                      VARCHAR (50)    NULL,
    [LOB]                         VARCHAR (50)    NULL,
    [CsplnProductSubPlanName]     VARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([mbrStg2_MbrDataUrn] ASC),
    CONSTRAINT [CK_MbrStg2_MbrData_stgRowStatus] CHECK ([stgRowStatus]='Exported' OR [stgRowStatus]='Valid' OR [stgRowStatus]='Loaded' OR [stgRowStatus]='Not Valid' OR [stgRowStatus]='Dups')
);

